name: Node.js CI

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install & Fetch
        run: |
          npm install --no-package-lock --no-save puppeteer@7.0.1 csvtojson@2.0.10
          npm run fetch
      - name: Git Add & Commit 
        run: | 
          git config --local user.email "bot@github.com"
          git config --local user.name "GitHub Action Bot"
          git add -A
          git commit --allow-empty -m "Updated Results"
      - name: Git Push
        run: git push
